variables:
  DOCKER_DRIVER: overlay

stages:
  - test
  - build
  - run

build:
  image: docker:18.06
  services:
   - docker:dind
  tags:
    - docker
  stage: build
  only:
    - master
  script:
    - docker build -t "$CI_PROJECT_PATH:latest" .
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker push "$CI_PROJECT_PATH:latest"

build-test:
  image: docker:18.06
  services:
   - docker:dind
  tags:
    - docker
  stage: build
  except:
    - master
  script:
    - docker build -t "$CI_PROJECT_PATH:latest" .
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
