image: docker:stable

stages:
  - test
  - build
  - run

variables:
  # When using dind service we need to instruct docker, to talk with the
  # daemon started inside of the service. The daemon is available with
  # a network connection instead of the default /var/run/docker.sock socket.
  #
  # The 'docker' hostname is the alias of the service container as described at
  # https://docs.gitlab.com/ee/ci/docker/using_docker_images.html#accessing-the-services
  #
  # Note that if you're using Kubernetes executor, the variable should be set to
  # tcp://localhost:2375 because of how Kubernetes executor connects services
  # to the job container
  DOCKER_HOST: tcp://docker:2375/
  # When using dind, it's wise to use the overlayfs driver for
  # improved performance.
  DOCKER_DRIVER: overlay2

services:
  - docker:dind

before_script:
  - docker info

tags:
  - docker

build:
  stage: build
  only:
    - master
  script:
    - docker build -t "$CI_PROJECT_PATH:latest" .
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
    - docker push "$CI_PROJECT_PATH:latest"

build-test:
  stage: build
  except:
    - master
  script:
    - docker build -t "$CI_PROJECT_PATH:latest" .
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
